services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: spring:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/login
      - SPRING_DATASOURCE_USERNAME=${db_user}
      - SPRING_DATASOURCE_PASSWORD=${db_password}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
      - SPRING_FLYWAY_ENABLED=true
      - SPRING_FLYWAY_LOCATIONS=classpath:db/migration
    networks:
      - backend
