version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: chamagol
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/chamagol
      - SPRING_DATASOURCE_USERNAME=${db_user}
      - SPRING_DATASOURCE_PASSWORD=${db_password}
      - SPRING_JPA_HIBERNATE_SHOW_SQL=true
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - jwt_secret=${jwt_secret}
      - MERCADO_PAGO_ACCESS_TOKEN=${MERCADO_PAGO_ACCESS_TOKEN}
      - MERCADO_PAGO_WEBHOOK_SECRET=${MERCADO_PAGO_WEBHOOK_SECRET}
      - NEXT_PUBLIC_MERCADO_PAGO_PUBLIC_KEY=${NEXT_PUBLIC_MERCADO_PAGO_PUBLIC_KEY}
      - mail_password=${mail_password}
      - mail_username=${mail_username}
      - mercado_pago_webhook=${mercado_pago_webhook}
      - APP_URL=${APP_URL}
    restart: always
    network_mode: host
