spring:
  application:
    name: login
  datasource:
    url: jdbc:postgresql://localhost:5432/chamagol
    username: ${db_user}
    password: ${db_password}
    hikari:
      maximum-pool-size: 32        # Até 2x núcleos, para 4 vCPU
      minimum-idle: 8              # 1/4 do máximo
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 15000    # Reduzido para resposta mais rápida
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false                # Desabilitado para produção
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail_username}
    password: ${mail_password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  forward-headers-strategy: framework
  error:
    include-stacktrace: never
  port: 8080
  address: 0.0.0.0
  tomcat:
    threads:
      max: 100                     # 4 vCPU suporta até 100 threads simultâneas
      min-spare: 16                # 1 por vCPU
    accept-count: 300              # Fila de requisições aguardando thread
    connection-timeout: 10000      # Timeout de conexão menor para liberar recursos
    keep-alive-timeout: 60000
    max-connections: 2000          # Limite de conexões simultâneas
logging:
  level:
    root: INFO
    org:
      springframework:
        security: WARN
api:
  url: ${APP_URL}
  security:
    token:
      secret: ${jwt_secret:my-secret-key}
      refresh:
        expiration: 10080
management:
  endpoints:
    web:
      exposure:
        include: health, metrics
  metrics:
    enable:
      all: true
